### ISSUE TITLE
Unset relationship causes error

### ISSUE THREAD

**Issue by Redsandro** [Redsandro/jsonapi-server-mini#6]
__TypeError: Cannot read property 'id' of `null`__ at `/lib/helpers/getModelData.js:25:17`

```
TypeError: Cannot read property 'id' of null
    at Object.keys.reduce (/src/node_modules/jsonapi-server-mini/lib/helpers/getModelData.js:25:17)
    at Array.reduce (<anonymous>)
    at getModelData (/src/node_modules/jsonapi-server-mini/lib/helpers/getModelData.js:19:36)
    at /src/node_modules/jsonapi-server-mini/lib/pipeline/updateOne.js:15:18
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node_modules/express/lib/router/route.js:137:13)
    at /src/utils/authn.js:22:3
    at /src/node_modules/jsonwebtoken/verify.js:223:12
    at getSecret (/src/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/src/node_modules/jsonwebtoken/verify.js:94:10)
    at module.exports (/src/utils/authn.js:17:6)
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node_modules/express/lib/router/route.js:137:13)
    at /src/node_modules/jsonapi-server-mini/lib/routeMapper.js:86:8
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at /src/node_modules/express/lib/router/index.js:281:22
    at param (/src/node_modules/express/lib/router/index.js:354:14)
    at param (/src/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/src/node_modules/express/lib/router/index.js:410:3)
```

https://github.com/Redsandro/jsonapi-server-mini/blob/master/lib/helpers/getModelData.js#L25

**Comment by Redsandro** [comment]
Strangely, `get(value, 'data.id')` does not return `undefined` but throws the following error:

__TypeError: Cannot read property 'id' of `null`__
    at __path.split.every.el__ (`/src/node_modules/jsonapi-server-mini/index.js:24:78`)

```
TypeError: Cannot read property 'id' of null
    at path.split.every.el (/src/node_modules/jsonapi-server-mini/index.js:24:78)
    at Array.every (<anonymous>)
    at global.get (/src/node_modules/jsonapi-server-mini/index.js:24:55)
    at Object.keys.reduce (/src/node_modules/jsonapi-server-mini/lib/helpers/getModelData.js:25:6)
    at Array.reduce (<anonymous>)
    at getModelData (/src/node_modules/jsonapi-server-mini/lib/helpers/getModelData.js:19:36)
    at /src/node_modules/jsonapi-server-mini/lib/pipeline/updateOne.js:15:18
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node_modules/express/lib/router/route.js:137:13)
    at /src/utils/authn.js:22:3
    at /src/node_modules/jsonwebtoken/verify.js:223:12
    at getSecret (/src/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/src/node_modules/jsonwebtoken/verify.js:94:10)
    at module.exports (/src/utils/authn.js:17:6)
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node_modules/express/lib/router/route.js:137:13)
    at /src/node_modules/jsonapi-server-mini/lib/routeMapper.js:86:8
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at /src/node_modules/express/lib/router/index.js:281:22
```

I'm really curious as to why this is. It will throw `undefined` for anything else. But no time. Workaround and close this.
